import type { Product } from './types';

const products: Product[] = [
  {
    id: '1',
    name: 'AuraShield Case for iPhone 15',
    description: 'Slim, protective, and stylish case.',
    longDescription: 'The AuraShield case offers military-grade drop protection in a slim, pocket-friendly design. Its crystal-clear back showcases your phone\'s original look, while the reinforced corners absorb shock from impacts. A raised bezel protects your screen and camera from scratches.',
    price: 29.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'phone case',
    brand: 'AuraShield',
    type: 'Case',
    rating: 4.8,
    reviews: [
      { id: 'r1', author: 'Jane D.', rating: 5, comment: 'Fits perfectly and feels great in hand!', date: '2023-10-15' },
      { id: 'r2', author: 'Mike P.', rating: 4, comment: 'Good protection, but the clear back gets fingerprints easily.', date: '2023-10-12' },
    ],
  },
  {
    id: '2',
    name: 'VoltSprint 45W GaN Charger',
    description: 'Ultra-fast charging in a compact size.',
    longDescription: 'Experience next-level charging with the VoltSprint 45W GaN charger. Using advanced Gallium Nitride technology, it delivers high-speed power to your devices in a fraction of the size of traditional chargers. Perfect for travel and decluttering your workspace.',
    price: 34.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'phone charger',
    brand: 'VoltSprint',
    type: 'Charger',
    rating: 4.9,
    reviews: [
      { id: 'r3', author: 'Chris G.', rating: 5, comment: 'Charges my phone incredibly fast. A game changer!', date: '2023-11-01' },
    ],
  },
  {
    id: '3',
    name: 'CrystalGuard Screen Protector',
    description: '9H hardness tempered glass protector.',
    longDescription: 'Protect your investment with the CrystalGuard screen protector. Made from 9H hardness tempered glass, it resists scratches from keys, coins, and other sharp objects. The ultra-thin design maintains perfect touch sensitivity and an oleophobic coating repels fingerprints.',
    price: 15.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'screen protector',
    brand: 'CrystalGuard',
    type: 'Screen Protector',
    rating: 4.6,
    reviews: [
      { id: 'r4', author: 'Sarah L.', rating: 5, comment: 'Easy to install and practically invisible.', date: '2023-09-20' },
      { id: 'r5', author: 'Ben T.', rating: 4, comment: 'Saved my screen from a nasty drop!', date: '2023-09-25' },
    ],
  },
  {
    id: '4',
    name: 'EchoBuds Pro Wireless Earbuds',
    description: 'Immersive sound with active noise cancellation.',
    longDescription: 'Dive into your music with EchoBuds Pro. These wireless earbuds feature advanced active noise cancellation to block out distractions, a transparency mode to hear your surroundings, and custom-tuned drivers for rich, detailed audio. Enjoy up to 8 hours of playback on a single charge.',
    price: 129.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'wireless earbuds',
    brand: 'EchoBuds',
    type: 'Headphones',
    rating: 4.7,
    reviews: [
      { id: 'r6', author: 'Alex R.', rating: 5, comment: 'The noise cancellation is amazing for my commute.', date: '2023-10-05' },
    ],
  },
  {
    id: '5',
    name: 'GripMount Magnetic Car Mount',
    description: 'Secure and convenient car phone holder.',
    longDescription: 'The GripMount provides a strong, secure hold for your phone while you drive. Its powerful magnets and slim metal plate ensure your device stays put, even on bumpy roads. The 360-degree rotation allows for perfect viewing angles for navigation.',
    price: 24.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'car mount',
    brand: 'GripMount',
    type: 'Car Mount',
    rating: 4.5,
    reviews: [],
  },
  {
    id: '6',
    name: 'AuraShield Case for Pixel 8',
    description: 'Slim, protective, and stylish case.',
    longDescription: 'The AuraShield case offers military-grade drop protection in a slim, pocket-friendly design. Its crystal-clear back showcases your phone\'s original look, while the reinforced corners absorb shock from impacts. A raised bezel protects your screen and camera from scratches.',
    price: 29.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'pixel case',
    brand: 'AuraShield',
    type: 'Case',
    rating: 4.7,
    reviews: [],
  },
  {
    id: '7',
    name: 'DuraWeave Braided USB-C Cable',
    description: 'Durable 6ft nylon-braided cable.',
    longDescription: 'Tired of flimsy cables? The DuraWeave is built to last. Its double-braided nylon exterior and reinforced connectors can withstand over 25,000 bends. The 6ft length provides extra convenience for charging from anywhere.',
    price: 19.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'charging cable',
    brand: 'VoltSprint',
    type: 'Charger',
    rating: 4.9,
    reviews: [
        { id: 'r7', author: 'Tom H.', rating: 5, comment: 'Finally a cable that doesn\'t break in a month!', date: '2023-11-10' },
    ],
  },
    {
    id: '8',
    name: 'AcousticFlow Open-Ear Headphones',
    description: 'Stay aware of your surroundings while listening.',
    longDescription: 'Perfect for runners and cyclists, the AcousticFlow headphones use bone conduction technology to deliver audio without blocking your ears. Stay safe and aware of your environment while enjoying your favorite podcasts and music. They are lightweight, sweat-resistant, and comfortable for all-day wear.',
    price: 89.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'bone conduction',
    brand: 'EchoBuds',
    type: 'Headphones',
    rating: 4.4,
    reviews: [],
  },
  {
    id: '9',
    name: 'FlexiGrip Silicone Case for Galaxy S24',
    description: 'Soft-touch silicone with a microfiber lining.',
    longDescription: 'The FlexiGrip case feels as good as it looks. The silky, soft-touch finish of the silicone exterior provides excellent grip, while a soft microfiber lining on the inside helps protect your phone from scratches. Available in a variety of vibrant colors.',
    price: 25.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'silicone case',
    brand: 'FlexiGrip',
    type: 'Case',
    rating: 4.6,
    reviews: [],
  },
  {
    id: '10',
    name: 'PrivacyGuard Screen Protector',
    description: 'Keep your screen private from prying eyes.',
    longDescription: 'The PrivacyGuard screen protector features a two-way privacy filter that darkens your screen when viewed from the side. It\'s perfect for using your phone in public spaces. Made from the same tough 9H tempered glass as our CrystalGuard protectors.',
    price: 19.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'privacy screen',
    brand: 'CrystalGuard',
    type: 'Screen Protector',
    rating: 4.5,
    reviews: [],
  },
    {
    id: '11',
    name: 'PowerDeck Trio Wireless Charging Pad',
    description: 'Charge your phone, watch, and earbuds simultaneously.',
    longDescription: 'Declutter your nightstand with the PowerDeck Trio. This sleek charging station features dedicated spots to wirelessly charge your phone, smartwatch, and wireless earbuds all at once. An intelligent chipset ensures optimal charging speeds for each device.',
    price: 79.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'charging station',
    brand: 'VoltSprint',
    type: 'Charger',
    rating: 4.7,
    reviews: [
        { id: 'r8', author: 'Emily R.', rating: 5, comment: 'So convenient to charge everything in one place.', date: '2023-11-02' },
    ],
  },
  {
    id: '12',
    name: 'TerraShell Eco-Friendly Case',
    description: 'Compostable case made from plant-based materials.',
    longDescription: 'Protect your phone and the planet with the TerraShell case. Made from 100% compostable and plant-based materials, it provides excellent drop protection while being environmentally friendly. When you\'re done with it, you can compost it at home!',
    price: 39.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'eco friendly',
    brand: 'TerraShell',
    type: 'Case',
    rating: 4.8,
    reviews: [],
  },
];

export function getProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}
