
import type { Product } from './types';

export const dummyProducts: Product[] = [
  {
    id: '1',
    name: 'Microscope',
    description: 'High-precision microscope for detailed repair work.',
    longDescription: 'This professional-grade microscope is essential for any serious phone repair technician. With powerful magnification and clear optics, it allows you to see the smallest components with ease, making intricate soldering and board-level repairs possible. The adjustable stand and lighting ensure a comfortable and well-lit workspace.',
    price: 299.99,
    image: 'https://storage.googleapis.com/gemini-studio-assets/business-website/43a6d9b5-25c7-4560-8451-aa3b32087e59.png',
    data_ai_hint: 'repair microscope',
    brand: 'Pro-Tech',
    type: 'Tools',
    rating: 4.9,
    reviews: [],
    isFeatured: true,
    dateAdded: '2023-11-28',
    stock: 25,
  },
  {
    id: '3',
    name: 'iPhone 14 Pro Max Screen',
    description: 'Vibrant and responsive OLED replacement screen.',
    longDescription: 'Restore your iPhone 14 Pro Max to its former glory with this high-quality OLED screen replacement. It offers the same vibrant colors, deep blacks, and responsive touch as the original. Each kit includes the necessary tools for installation.',
    price: 189.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'phone screen',
    brand: 'ScreenSavvy',
    type: 'Screen',
    rating: 4.7,
    reviews: [],
    isFeatured: true,
    dateAdded: '2023-11-15',
    stock: 50,
  },
  {
    id: '5',
    name: 'Pro-Tech 25-in-1 Repair Toolkit',
    description: 'Essential tools for any phone repair.',
    longDescription: 'The Pro-Tech toolkit has everything you need for DIY phone repairs. It includes various pentalobe, Phillips, and flathead screwdrivers, spudgers, suction cups, and picks, all housed in a compact, organized case. Made with high-quality CR-V steel for durability.',
    price: 24.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'repair tools',
    brand: 'Pro-Tech',
    type: 'Tools',
    rating: 4.9,
    reviews: [],
    isFeatured: true,
    dateAdded: '2023-11-20',
    stock: 200,
  },
  {
    id: '6',
    name: 'X650 C/F',
    description: 'OEM-grade replacement for faulty charging ports.',
    longDescription: 'Fix charging issues with your phone with this replacement flex cable. This component includes the USB-C port, primary microphone, and cellular antenna connections. Ensures reliable charging and data sync.',
    price: 22.50,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'flex cable',
    brand: 'PartPerfect',
    type: 'Charging Flex',
    rating: 4.6,
    reviews: [],
    dateAdded: '2023-11-18',
    stock: 150,
  },
    {
    id: '8',
    name: 'iPhone 12 P/F',
    description: 'Replacement for power button and volume controls.',
    longDescription: 'This flex cable assembly replaces the power button, volume buttons, and mute/ring switch for various iPhone models. Ideal for fixing unresponsive or malfunctioning buttons. Please select your specific model before ordering.',
    price: 18.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'volume button',
    brand: 'PartPerfect',
    type: 'Power Flex',
    rating: 4.5,
    reviews: [],
    dateAdded: '2023-11-08',
    stock: 80,
  },
  {
    id: '9',
    name: 'Pixel 7 Pro Screen',
    description: 'High-quality screen with included adhesive.',
    longDescription: 'Bring your Google Pixel 7 Pro display back to life. This kit includes a high-fidelity screen and pre-cut adhesive for a secure, water-resistant fit. The display offers accurate colors and touch response.',
    price: 145.00,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'pixel screen',
    brand: 'ScreenSavvy',
    type: 'Screen',
    rating: 4.7,
    reviews: [],
    dateAdded: '2023-10-25',
    stock: 65,
  },
  {
    id: '10',
    name: 'Samsung Galaxy S22 Ultra Backglass',
    description: 'OEM-quality backglass replacement with adhesive.',
    longDescription: 'Replace your cracked or shattered Samsung Galaxy S22 Ultra backglass with this high-quality replacement part. It comes with pre-installed adhesive for a secure fit and matches the original look and feel.',
    price: 49.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'phone backglass',
    brand: 'GlassGuard',
    type: 'Backglass',
    rating: 4.8,
    reviews: [],
    dateAdded: '2023-11-25',
    stock: 120,
  },
   {
    id: '11',
    name: 'X559 C/F',
    description: 'Replacement charging port for various models.',
    longDescription: 'Fix charging issues with your device using the X559 replacement flex cable. Ensures reliable charging and data sync for compatible models.',
    price: 21.99,
    image: 'https://placehold.co/600x600.png',
    data_ai_hint: 'charging port',
    brand: 'PartPerfect',
    type: 'Charging Flex',
    rating: 4.5,
    reviews: [],
    dateAdded: '2023-11-22',
    stock: 180,
  },
  ...Array.from({ length: 60 }, (_, i) => {
    const id = (i + 12).toString();
    const typeOptions: Product['type'][] = ['Screen', 'Tools', 'Charging Flex', 'Power Flex', 'Backglass', 'Glass'];
    const brandOptions = ['ScreenSavvy', 'Pro-Tech', 'PartPerfect', 'GlassGuard', 'FixIt'];
    const type = typeOptions[i % typeOptions.length];
    const brand = brandOptions[i % brandOptions.length];
    
    // Deterministic generation based on index `i`
    const price = parseFloat(((i * 3.14) % 185 + 15).toFixed(2));
    const rating = parseFloat((((i * 0.1) % 1.5) + 3.5).toFixed(1));
    const stock = (i * 17) % 250;
    const baseDate = new Date('2023-01-01').getTime();
    const dateOffset = i * 24 * 60 * 60 * 1000 * 3; // 3 days per product
    const date = new Date(baseDate + dateOffset).toISOString().split('T')[0];


    return {
        id: id,
        name: `${brand} Model ${id}`,
        description: `A high-quality ${type.toLowerCase()} for various devices.`,
        longDescription: `This is a premium ${type.toLowerCase()} from ${brand}, designed for reliability and performance. Model ${id} ensures perfect compatibility and function.`,
        price: price,
        image: `https://placehold.co/600x600.png`,
        data_ai_hint: `${type.toLowerCase().split(' ')[0]}`,
        brand: brand,
        type: type,
        rating: rating,
        reviews: [],
        isFeatured: i < 3,
        dateAdded: date,
        stock: stock,
    };
  }),
];
